### ISSUE TITLE
Add common errors and what to do

### ISSUE THREAD

**Issue by wilsonmar** [jlord/git-it-electron#119]
Right now, git-it says "try again", which to me is not very helpful. It would be useful if I get a clue what to fix by looking at errors others have encountered so I can get past the block. Kinda like StackOverflow built in. The ability to recover from mistakes is as big a part of the learning as being comfortable typing the commands.  For example, in the GITHUBBIN module, is there an interpretation of this response to git-it verify so I can write the correct command?:

```
ACTUAL                             EXPECTED
------                             --------
"{ [Error: Command failed: /bin/sh -c git config user.username" != "Username added to Git config!"
"]"                             != "You're on GitHub!"            
"  killed: false,"              != "Username same on GitHub and"  
"  code: 1,"                    != "Git config!"                  
"  signal: null,"               != ""                             
"  cmd: '/bin/sh -c git config user.username' }" != null                           
""                              != null                           
# FAIL
```
Another example: in the branches module, what did I do wrong and what should I do instead if I get this message?

```
remote: Permission to jlord/patchwork.git denied to wilsonmar.
fatal: unable to access 'https://github.com/jlord/patchwork/': The requested URL returned error: 403
```

**Comment by jlord** [comment]
@wilsonmar are you referring to using Git-it app in the terminal and is located at [jlord/git-it](https://github.com/jlord/git-it)? 

This repository is for the desktop version which does contain tips for commonly missed parts of challenges:

![screen shot 2016-04-20 at 9 39 03 am](https://cloud.githubusercontent.com/assets/1305617/14682732/c1fa4c00-06db-11e6-8fd8-f3c8a6821029.png)

**Comment by wilsonmar** [comment]
Yes, that helps. But I think it would be even more helpful to learners if they see the same error messages that come up in the tutorial. A big part of the skill people learn is troubleshooting.
BTW, learning researchers say that learners retain skills longer and stronger if they've encountered an error which they overcame.

**Comment by wilsonmar** [comment]
On the git-it client module Githubbin, what should one do if this error returns on Verify:

Username added to Git config!
GitHub account matching Git config username wasn't found.

**Comment by jlord** [comment]
> But I think it would be even more helpful to learners if they see the same error messages that come up in the tutorial

Some of the sections do do this. I do want to help users troubleshoot and have opened this issue https://github.com/jlord/git-it-electron/issues/74 with an idea I particularly like. 

I do not doubt that reinforcement is important, as you suggest, but alas I am but one person with not enough spare hours 😓 I hope to make this app as useful as I can with the time I do have. 

> git-it client module

I don't know what you're referring to here—the terminal-based Git-it or the one in this repository, Git-it Electron. If the latter, then the user would see a suggestion with a similar title under 'Didn't Pass?'

Thank you for your suggestions—since this touches on the same underlying idea (creating better error feedback system so users can troubleshoot) as #74 I'm going to close it as a duplicate.
