### ISSUE TITLE
Fatal error with ssh remote

### ISSUE THREAD

**Issue by jeffebert** [jlord/git-it-electron#129]
I normally use ssh remotes, so I continued doing so in the git-it tutorial. This worked fine until I got to "Pull Never Out of Date". The verify step fails with a fatal error "Permission denied (publickey)."  After changing the remote url to use https, the verify step passed.

**Comment by jlord** [comment]
I'm not sure why it would fail. That challenge is just running `fetch --dry-run` in a child process to verify and if SSH worked on other challenges I'd _think_ it would work here too, but that's just a guess. 

GitHub recommends HTTPS in general and it's easier to get set up so that's why it's recommended in Git-it, too. If you can figure it out and submit a pull request that would be awesome, but I'm going to close this for now since HTTPS is what we're recommending.
