### ISSUE TITLE
Trouble with branches are not just for birds challenge

### ISSUE THREAD

**Issue by bitakazemi** [jlord/git-it-electron#133]
@jlord :
I do all the steps as said in the tutorial however I get :
 remote: Permission to jlord/patchwork.git denied to bitakazemi.
fatal: unable to access 'https://github.com/jlord/patchwork/': The requested URL returned error: 403

**Comment by jlord** [comment]
Hiya!

You should be pushing to _your_ branch on _your fork_ and not the original `jlord/patchwork`. You don't have access to that repository so that's why you get that error 😄 

Check the remotes that you have set up, you should have two. One to pull from the original named `upstream` and one to push/pull from your fork  named `origin`.

```bash
git remote -v
```
