### ISSUE TITLE
Missing module 'request'

### ISSUE THREAD

**Issue by isonet** [jlord/git-it-electron#160]
With the [latest](https://github.com/jlord/git-it-electron/releases/tag/4.2.1) release, the request module seems to be missing.

As a workaround I ran `npm install` in `Git-it-Windows-ia32\resources\app\` which solved the problem.

![2016-09-16](https://cloud.githubusercontent.com/assets/2650326/18597559/d66b7a40-7c4e-11e6-8a52-0e88876efd7b.png)

This happened on Windows 10 64-bit (1607 - 14393.187)

**Comment by jlord** [comment]
Oh, strange. Thanks for opening this issue!

**Comment by codejunky** [comment]
I got the same problem on my Mac. running npm install in Git-it.app/Resources/app solves the problem.

**Comment by isonet** [comment]
If I'm understanding this correctly the faulty build was generated by travis?

This might be due to the fact that travis is using a version of npm below 3.0 `Now using node v0.12.15 (npm v2.15.1)` (From the log : https://s3.amazonaws.com/archive.travis-ci.org/jobs/158645999/log.txt)

It might be enough to just update the .travis.yml and specify a more recent node and npm version.

**Comment by Git-Jiro** [comment]
The solution of @codejunky worked for me too!

**Comment by jlord** [comment]
Hmm, this is very weird because `request` is in the `package.json` and it should be getting bundled into the app with everything else. 

But you're right, if I check the latest release, it doesn't include `request` even though it seems to be in the version I built to put in the releases 🤔 

I will build again and double check `request` makes it in. 

<img width="771" alt="screen shot 2016-10-16 at 9 56 54 am" src="https://cloud.githubusercontent.com/assets/1305617/19414695/dbe2a64c-9387-11e6-920d-6924f70c4575.png">

**Comment by jlord** [comment]
New version out: https://github.com/jlord/git-it-electron/releases/tag/4.2.2
