### ISSUE TITLE
Incorrect URI in the last step of "Merge Tada"?

### ISSUE THREAD

**Issue by thisisthefuture** [jlord/git-it-electron#165]
In the last step git-it says, 

> Pull from Upstream
>
> And last but not least, the original has changed since your pull request was merged—Reporobot added > your name to the website! If you pull in these changes from upstream you'll be up to date and have that > version too. _You can actually see it live as well at: yourusername.github.io/patchwork_.
>
> To pull from the original upstream:
>
> git pull upstream gh-pages

Yet going to thisisthefuture.github.io/patchwork gives me a 404... because I assume I never actually created a github page. Should `yourusername.github.io/patchwork` be instead `jlord.github.io/patchwork`, or that line be omitted entirely? 

I see that the page there has been updated with my completion.

**Comment by jlord** [comment]
Because you have forked the project at `jlord/patchwork`, which is a website with a `gh-pages` branch, you will also have a website. Your fork's website will be under your account and should be located at `yourusername.github.io/patchwork`, once you have merged your changes into the `gh-pages` branch of your fork. 

Sometimes it takes GitHub a few minutes to build a new page, are you still getting a 404? If so have you merged your `add-thisisthefuture` branch into the `gh-pages` branch?

Closing out now as the text in Git-it is correct, but let me know if you're still unable to see your fork's page. Thanks!

**Comment by thisisthefuture** [comment]
It's been over a few week, but the URI works now! 
Not sure how long it took it for it to appear. ¯\_(ツ)_/¯
