### ISSUE TITLE
"modified:   contributors/add-AaronCallahan.txt" from fresh clone

### ISSUE THREAD

**Issue by upnorth** [jlord/git-it-electron#171]
Fairly new to Git but the guide has been very interesting and worked well up to getting reporobot on as a collaborator (doesn´t accept invite). But I found the solution and jumped to request pull.

Here I got this odd error from "git status" in my local repository. I tried to remove, add and rename the file (with all lowercase) but no matter what I come up with I can´t push my own file to my clone. I was able to "match" the file with the last commit to Git, but then reporobot detected my upload of more than my own file, so I couldn´t complete the guide anyway.

Haven´t seen any other people reporting this error but I have run out of ideas for how to fix it or reset the repository to where the file hasn´t been modified, so I thought I would at least let you know. It was mainly the mechanics of local/remote, master/origin and fork/clone that confused me before, which I understand better now at least.

**Comment by jlord** [comment]
This has come up a few times and I think it has to do with different operating systems handling letter case differently. 

I don't have a fix for that just yet, but hope that clearing out the `/contributors` directory more frequently will help. Since that fix would happen on the server (and not in this repo, with the app's code) and I have an issue open for it, I'll close this one here and crosslink 🔗 https://github.com/jlord/reporobot/issues/29
