### ISSUE TITLE
two step authentication

### ISSUE THREAD

**Issue by spences10** [jlord/git-it-electron#173]
I was trying to do the git-it challenges for FreeCodeCamp on a c9 instance and couldn't ```git push origin master``` as I had two step auth enabled on the account, I had to disable it then re-enable is this a known issue?

**Comment by jlord** [comment]
I don't have any experience with c9 so I can't say if Git-it is compatible with it or not. In general 2fA should not be a problem.

> couldn't `git push origin master`

Git-it doesn't interfere with normal Git operations, so if you're having an issue with Git on c9 my guess is it's probably not Git-it.

**Comment by spences10** [comment]
I wasn't sure if it was a known issue or not, I'll log a ticket with the c9 guys and close this one

**Comment by IonicaBizau** [comment]
@jlord @spences10 I don't think that's specific to c9. This happens if you use https authentication. Instead of entering the password, you can [enter an access token](https://github.com/settings/tokens) and that will authenticate you, even if you have two factor authentication enabled.

See [this article](https://github.com/blog/1614-two-factor-authentication) (search for *How does it work for command-line Git?*). :memo: 

Another way is to set up SSH authentication and c9 will use that as well.

`git remote -v` should be able to tell you if you're using HTTPs or SSH urls (probably you use HTTPs).

**Comment by spences10** [comment]
thanks for this @IonicaBizau I'll take a look at this next time, just fyi @jlord I have a Ruby environment set up on c9 and I was able to ```git push origin master``` from there with just entering my uname and pwrd. This is with 2fa enabled on GitHub

Should this be reopened or shall we just refer to @IonicaBizau's notes??

**Comment by IonicaBizau** [comment]
@spences10 Can you post the outputs of `git remote -v` for both repos? I do think that in one you have ssh (the Ruby one) and in the other you have https.

**Comment by spences10** [comment]
Here you go @IonicaBizau 
Ruby:
```
spences10:~/workspace/spences10.github.io (master) $ git remote -v
origin  https://github.com/spences10/spences10.github.io (fetch)
origin  https://github.com/spences10/spences10.github.io (push)
```
Node:
```
spences10:~/workspace/patchwork (gh-pages) $ git remote -v
origin  https://github.com/spences10/patchwork (fetch)
origin  https://github.com/spences10/patchwork (push)
upstream        https://github.com/jlord/patchwork.git (fetch)
upstream        https://github.com/jlord/patchwork.git (push)
```

**Comment by IonicaBizau** [comment]
@spences10 OK, so both are https.

> I have a Ruby environment set up on c9 and I was able to `git push origin master` from there with just entering my uname and pwrd. 

That shouldn't be possible if you have two factor authentication enabled. Can you double check that?
Enable 2FA and try to push some changes from the Ruby one.

**Comment by spences10** [comment]
@IonicaBizau you're right :sweat_smile: looks like I didn't re-enable it :blush: 

I'll re-enable and try again

**Comment by spences10** [comment]
@IonicaBizau that was it, thank you!
```
spences10:~/workspace/spences10.github.io (master) $ git push origin master
Username for 'https://github.com': spences10
Password for 'https://spences10@github.com': 
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 386 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/spences10/spences10.github.io
   3499cf2..efcc4f7  master -> master
```

Do you know what scopes are needed for the token? I thought it was ```admin:repo_hook``` but it failed so I just enabled them all and it worked, I don't think having them all enabled it a wise move though.

**Comment by IonicaBizau** [comment]
@spences10 Just the `repo` one should be enough. Glad to hear it was fixed! 😁 

To not waste the time pasting the token every time, you can use it in the url:

```
git remote set-url origin https://spences10:your-token@github.com/spences10/spences10.github.io
```

(replace `your-token` with the token)

Then you should be able to `git push`, even with 2FA enabled. 🚀

**Comment by spences10** [comment]
:medal_sports: thanks @IonicaBizau this will come in handy

**Comment by IonicaBizau** [comment]
@spences10 Happy to help! 😊

**Comment by jlord** [comment]
@IonicaBizau Thanks!

@spences10 Glad you got that sorted. My head was definitely in the _I have 2fA and it works so it must be something else_ space because there have been some weird issues with C9 before. I forgot I have my credentials cached :)

This doesn't come up as a problem too often. I think most people either don't have 2fA set up or have things cached also, but I see there is a PR to add some guidance https://github.com/jlord/git-it-electron/pull/169.

I've been on a computer break but am slowly emerging so hopefully will make this less of a bump 🔜

**Comment by spences10** [comment]
@IonicaBizau I used the link you posted for another repository adding my token, it worked!!

```git remote set-url origin https://spences10:your-token@github.com/spences10/spences10.github.io```

I used ```git push --force``` :scream:

It also added the new repository over my ```spences10/spences10.github.io```  repo! lol :stuck_out_tongue_winking_eye: luckily I had a clone of the repo on my phone and have just restored with history!! Phew :relieved: 

Thanks again! and sorry to clog up this issue with non related stuff @jlord :blush:

**Comment by IonicaBizau** [comment]
@spences10 Yeah, `--force` should be use with care. :smile: Hopefully this issue will be usefull to other guys having the same problem.
