### ISSUE TITLE
Branches Aren't Just For Birds

### ISSUE THREAD

**Issue by Su739** [jlord/git-it-electron#210]
Error: Command failed: "E:\Git-it-Win-ia32\Git-it-Win-ia32\resources\app\assets\PortableGit\bin\git.exe " reflog show origin/add-Su739 fatal: ambiguous argument 'origin/add-Su739': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'

**Comment by KevinKunkee** [comment]
@jlord I just ran into this problem.

It appears it is going to keep coming back because a capital C on "Contributors" can be put in the commits by any contributor with a filesystem that ignores case.  I just submitted a pull request on patchwork to fix this again, but it won't last.

When I downloaded a zip of the repo, it had **_one_** "contributors" folder, but as soon as I unzipped it (or cloned the repo) in a case-sensitive filesystem, there were suddenly two folders--"Contributors" and "contributors".  In fact, there were add-username.txt files in **_both_**.

--Kevin
