### ISSUE TITLE
Can't spawn git on windows by default with cmd.exe

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#54]
by default cmd.exe doesn't have `git.exe` in its PATH. it's really complicated to set the path on windows, so instead if we're on windows we should have people install Git for Windows and then use this instead:

```js
exec('"' + p.join('C:', 'Program Files', 'Git', 'bin', 'git.exe') + '"', cb)
```

One caveat is it relies on them having a C: drive

All the code that does spawning will have to be updated to do `if (os.platform === 'win32') {}` to set the git cmd to the above value.

There might be a way override path when spawning on windows but I don't know how

**Comment by jlord** [comment]
cc @paulcbetts maybe you have some advice on a better way to have users tell us where their Git is? :pray:

**Comment by shiftkey** [comment]
This is also going to clash with Git Shell, which is deployed under `%LOCALAPPDATA%` and can differ between releases. I've had a few people reach out recently about this, so perhaps it's time for us to rethink this.

I also know that Visual Studio Code has a similar problem. I believe they expect Git to be on the user's PATH environment variable, so if you can't do a `git --version` or similar they prompt you to install it - which adds it to the PATH.

**Comment by jlord** [comment]
@shiftkey is there a way to open up CMD and make Git work?

I have GitHub Desktop and Git for Windows on my VM and Git's still not on my CMD path.. (I hope I'm saying these things correctly)

**Comment by IonicaBizau** [comment]
@jlord There is an option when you install Git on Windows. See [this](https://github.com/IonicaBizau/github-contributions#notes-for-installing-on-windows). Maybe that helps. :smile_cat: 

![](https://camo.githubusercontent.com/97c2f013eeff10a89a225b23d7b18cf4f88d6b96/687474703a2f2f692e696d6775722e636f6d2f554f6b7833356a2e706e67)

**Comment by paulcbetts** [comment]
It seems like the easiest way to solve this is via bundling Portable Git just like GitHub for Windows does.

**Comment by shiftkey** [comment]
@jlord there's a long and sordid tale here, but here's the basics:

 - when you install GitHub Desktop on Windows, we unpack a portable Git installation under `%LOCALAPPDATA%\GitHub - this resolves to something like C:\users\jlord\AppData\GitHub\
 - we don't add this to the user's PATH because we don't want to interfere with existing Git installations
 - the Git Shell shortcut is there to launch your desired shell (PowerShell, Git Bash or Cmd), with Git added to the PATH for just the lifetime of the shell. We also take care of things like ensuring `ssh-agent` is running, and that your credentials in GitHub Desktop are available in the shell
 - we often update our portable Git installation as part of updating GitHub Desktop, and due to how our install and update works the path can change between releases

So our current environment is around having an interactive shell for the user, rather than just being able to run commands against a local version of git.exe. This is something I'd like to change, but requires planning and prioritization around other work :cry:

**Comment by paulcbetts** [comment]
So basically, don't do anything @shiftkey says and listen to me instead :)

**Comment by shiftkey** [comment]
what @paulcbetts said

**Comment by jlord** [comment]
Haha thanks @shiftkey @paulcbetts! :balloon: :tada: Going for it!
