### ISSUE TITLE
GitHub Enterprise ready

### ISSUE THREAD

**Issue by EricDales** [jlord/git-it-electron#96]
Hi there, 

we're github enterprise users and would love to use git-it with our github enterprise server. Would it be possible to add such a setting ? 

Cheers !
Eric

**Comment by jlord** [comment]
Hiya!

It is probably possible but is not on my to-do list. Though it's all open source so I'd be happy to get pull requests for it! One would need to fork `jlord/patchwork`, `jlord/git-it-electron`, and `jlord/reporobot` and change them so that it used the internal servers and not github.com and the server that @reporobot lives on.
